### ISSUE TITLE
Remove the database file. Resets after every pull

### ISSUE THREAD

**Issue by siddhantkhandelwal** [sharifa2708/Checkmate2019#32]
Please remove the file db.sqlite3. It can cause trouble.

**Comment by dush-t** [comment]
You can remove it, but then you'll have to populate 14 questions in the questions model. Collision with a question block calls for a question from the Question model. If it does not find a question with the respective id, a very ugly error would come up. Added the database just for convenience, since it already has the questions I added.

**Comment by siddhantkhandelwal** [comment]
That's nice. 
But you can always make a population script that puts in neat model entries. 
Also, writing that script will not take more than 10 minutes.
[Take a look here](https://github.com/DominikSerafin/rango/blob/master/populate.py)
It makes debugging easy for everyone.
