### ISSUE TITLE
Google OAuth Integration

### ISSUE THREAD

**Issue by siddhantkhandelwal** [sharifa2708/Checkmate2019#6]
It would be nice if participants could register with their BITS mail.
django-allauth could be a possible solution.
Let's look into this.

**Comment by Saujas** [comment]
@aarjavjain1 have you integrated the feature with the main app? Work with @dush-t on this

**Comment by dush-t** [comment]
@Saujas I don't think we can do this with django-allauth. Not with django 2.1 at least. There appears to be some url pattern problem in the allauth library. 

Doing it any other way needs us to either totally change the data models (in a way that might create problems later) or handle sign up in a way such that it takes much more time than it does right now (because of the fact that both users in a team need to register separately at different times). Do we really need this feature?

**Comment by siddhantkhandelwal** [comment]
Closing this issue. This feature is not needed.
